apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops
  template:
    metadata:
      labels:
        app: demo-devops
    spec:
      containers:
        - name: app
          image: yasselreyes8x/demo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: demo-secrets
          env:
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: USE_POSTGRES
              value: "True"
            - name: DB_NAME
              value: "demo"
            - name: DB_USER
              value: "user"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
          #livenessProbe:   # No funciona en este caso
           # httpGet:
            #  path: /api/
             # port: 8000
           # initialDelaySeconds: 15
            #periodSeconds: 20
          #readinessProbe:
           # httpGet:
            #  path: /api/
             # port: 8000
            #initialDelaySeconds: 5
            #periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
