apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: demo-devops
  template:
    metadata:
      labels:
        app: demo-devops
    spec:
      containers:
        - name: app
          image: yasselreyes8x/demo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: "demo"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "db"               # debe coincidir con el nombre del Service de PostgreSQL
            - name: DB_PORT
              value: "5432"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_SETTINGS_MODULE
              value: "demo.settings"
          livenessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
