apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: supersecretkey123
  DB_NAME: demo
  DB_USER: user
  DB_PASSWORD: password
  DB_HOST: postgres
  DB_PORT: "5432"
