apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo-devops
spec:
  type: NodePort
  selector:
    app: demo-devops
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
